version: '3'

services:
    rst-service:
        build: ./rst-service # path is relative to docker-compose.yml location
        volumes:
            - ./rst-service:/usr/src/rst-service-api # mount point
        ports:
            - 5050:5050 # host:container
        depends_on:
            - feng
            - converter
        networks:
            - net

    feng:
        build: ./feng-hirst-service
        image: feng-hirst-service
        expose:
            - "8080"
        networks:
            net:
                aliases:
                    - feng
                         
    converter:
        build: ./rst-converter-service
        image: rst-converter-service
        expose:
            - "5000"
        networks:
            net:
                aliases:
                    - converter 
                    - conv

networks:
    net:
